server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_submission_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

